# Generated by Django 3.1.1 on 2020-09-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_posting_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='price',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='posting',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
