# Generated by Django 3.1.1 on 2020-10-02 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20200926_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='List_Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=300)),
                ('isbn', models.CharField(max_length=300)),
                ('subject', models.CharField(max_length=300)),
                ('class_used', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(max_length=300)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FromUser+', to=settings.AUTH_USER_MODEL, verbose_name='FromUser')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ToUser+', to=settings.AUTH_USER_MODEL, verbose_name='ToUser')),
            ],
        ),
        migrations.AddField(
            model_name='posting',
            name='book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.list_book', verbose_name='BookForSale'),
        ),
    ]
