# Generated by Django 3.1.1 on 2020-10-11 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_favorite_sjsu_user'),
        ('app', '0004_list_book_login_register'),
    ]

    operations = [
    ]
