# Generated by Django 3.1.1 on 2020-10-11 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_merge_20201010_2206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
