# Generated by Django 3.1.1 on 2020-10-11 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('app', '0011_delete_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SJSU_User',
        ),
    ]
