# Generated by Django 3.1.1 on 2020-09-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='price',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
