# Generated by Django 3.1.1 on 2020-10-02 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201002_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Book', to='app.list_book', verbose_name='BookForSale'),
        ),
    ]
