# Generated by Django 3.1.1 on 2020-10-02 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201002_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='book',
        ),
        migrations.AddField(
            model_name='posting',
            name='listed_book',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.list_book'),
        ),
    ]
