# Generated by Django 3.1.1 on 2020-10-02 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201002_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sjsu_id', models.CharField(max_length=9)),
                ('sjsu_pw', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='posting',
            name='listed_book',
        ),
        migrations.AddField(
            model_name='posting',
            name='book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Book', to='app.list_book', verbose_name='Book'),
            preserve_default=False,
        ),
    ]
